CREATE TABLE BAND (
	id SERIAL,
	name VARCHAR(255) NOT NULL,
	year_formed SMALLINT NOT NULL,
	year_dissolution SMALLINT,
	style VARCHAR(255) NOT NULL,
	origin VARCHAR(255) NOT NULL,
CONSTRAINT PK_BAND PRIMARY KEY(id));